In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer,MissingIndicator

In [2]:
df = pd.read_csv('train.csv',usecols=['Age','Fare','Survived'])

In [3]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [4]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [5]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [6]:
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)# so jya null hase tya by default mean thase and model ae rete train
X_test_trf = si.transform(X_test)

In [7]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(X_train_trf,y_train)
y_pred = clf.predict(X_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6145251396648045

## Missing Indicator

so ae su hoy k aek col ma lets say koi NA value che to aek seperate col banse
like
age ha 3 values and 1 NA
age_missing will be made which will have 3 False and 1 true

so models know how to diff between null and not null values

this doesnt work always
but if accuracy or r2 score is less then this is must try

In [8]:
mi = MissingIndicator()
si = SimpleImputer()

X_train_age_na = mi.fit_transform(X_train)
X_test_age_na = mi.transform(X_test)

X_train['Age_NA'] = X_train_age_na
X_test['Age_NA'] = X_test_age_na

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

clf.fit(X_train_trf2, y_train)
y_pred = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.6312849162011173

## OR

In [13]:
si = SimpleImputer(add_indicator=True)
X_train_trf3 = si.fit_transform(X_train)
X_test_trf3 = si.transform(X_test)

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train_trf3,y_train)
y_pred = clf.predict(X_test_trf3)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6312849162011173

## Gridsearch CV --> sklearn badha combinations lagave to see the best accuracy in which imputation technique

In [14]:
df = pd.read_csv('train.csv')

In [15]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [16]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [18]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
param_grid = {
    'preprocessor__num__imputer__strategy':['mean','median'],
    'preprocessor__cat__imputer__strategy':['most_frequent','constant'],
    'classifier__C':[0.1,1.0,10,100]
}
grid_search = GridSearchCV(clf,)