## Dummy Variable Trap

there are 3 categories/colours yellow,blue,red and we cant rank it like 0, 1, 2 in categories like we did in ordinal-label-encoding or else the model will think one colour is more imp than other

so we represent in binary so if colour iis yellow then it is 1 and rest 2 cols or colours are 0

this is known as Dummy Variable and it leads to dummy variable trap as then the input cols become dependent to each other and in ml we have to make all the input cols independent of eachother

so for n cols we drop the 1st col as if 2 colours are 0 then ofc the 3rd colour is the correct colour

when there are many many cols/categories we take the categories that are frequently used and put others in diff category like others and then aena Dummy Variable banse

In [58]:
import pandas as pd
import numpy as np

In [59]:
df=pd.read_csv('cars.csv')

In [60]:
df.sample(5)

           brand  km_driven    fuel         owner  selling_price
2156     Hyundai      15000  Petrol   First Owner         610000
7554  Mitsubishi     160000  Diesel  Second Owner        1250000
6375      Maruti      85000  Petrol   First Owner         185000
1041       Honda     100000  Diesel  Second Owner         450000
4518       Honda     120000  Diesel   First Owner         550000

In [61]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [62]:
df['brand'].nunique()

32

In [63]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [64]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

## One Hot Encoding using pandas

In [65]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int,drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

we dont use pd as pd doesnt remember the order of cols so everytime we run we get diff result so ml project ma cant be use so we use sklearn instead

In [66]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_tarin,y_test = train_test_split(df.drop('selling_price',axis=1),df['selling_price'],test_size=0.2,random_state=0)

In [67]:
from sklearn.preprocessing import OneHotEncoder

In [68]:
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype='int64')

In [69]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']]) # 2 sq brackets as we need in 2D arr

In [70]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [71]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape # 2 round brackets as tuple

(6502, 9)

In [72]:
counts = df['brand'].value_counts()

In [73]:
df['brand'].nunique()

32

In [74]:
threshold = 100

In [75]:
change = counts[counts<=threshold].index

In [76]:
pd.get_dummies(df['brand'].replace(change,'uncommon'),dtype=int,drop_first=True).sample(10)

,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
7900,0,0,0,0,0,1,0,0,0,0,0,0
1737,0,0,0,0,0,0,0,0,1,0,0,0
8052,0,0,1,0,0,0,0,0,0,0,0,0
7735,0,0,0,0,0,1,0,0,0,0,0,0
4900,0,1,0,0,0,0,0,0,0,0,0,0
3096,0,0,0,0,0,0,0,0,0,0,0,1
2467,0,0,0,0,1,0,0,0,0,0,0,0
1639,0,0,0,0,1,0,0,0,0,0,0,0
839,0,0,0,0,0,1,0,0,0,0,0,0
4584,0,0,0,0,0,1,0,0,0,0,0,0