in discretisation aek conti value ne discrete ma convert karye ahiya binary m aconvert karsu... like atla thi upr income to tax payers nitar nai

eg img processing like colourful to black and white so like aek threshold thi neeche black then white as 0 to 255 ni range ma hoy colours

In [12]:
import pandas as pd
import numpy as np


from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

from sklearn.compose import ColumnTransformer

In [13]:
df = pd.read_csv('train.csv')[['Age','Fare','SibSp','Parch','Survived']]

In [3]:
df.dropna(inplace=True)

In [4]:
df.shape

(714, 3)

In [5]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [14]:
df['family'] = df['SibSp'] + df['Parch']

In [15]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [16]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [19]:
clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
accuracy_score(y_test,y_pred)

0.6927374301675978

In [21]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,y,cv=10,scoring='accuracy'))

np.float64(0.6554431960049938)

In [22]:
from sklearn.preprocessing import Binarizer

In [28]:
trf=ColumnTransformer([
    ('bin',Binarizer(copy=False),['family'])
],remainder='passthrough')

In [29]:
X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)

In [30]:
pd.DataFrame(X_train_trf,columns=['family','Age','Fare'])

     family   Age     Fare
0       1.0   NaN  15.2458
1       0.0  31.0  10.5000
2       1.0  31.0  37.0042
3       0.0  20.0   4.0125
4       0.0  21.0   7.2500
..      ...   ...      ...
707     1.0  39.0  83.1583
708     1.0  19.0   7.8542
709     0.0   NaN   7.7333
710     1.0  36.0  17.4000
711     1.0  60.0  39.0000

[712 rows x 3 columns]

In [31]:
clf = DecisionTreeClassifier()
clf.fit(X_train_trf,y_train)
y_pred2 = clf.predict(X_test_trf)

accuracy_score(y_test,y_pred2)

0.6815642458100558

In [32]:
X_trf = trf.fit_transform(X)
np.mean(cross_val_score(DecisionTreeClassifier(),X_trf,y,cv=10,scoring='accuracy'))

np.float64(0.6532459425717853)